### ISSUE TITLE
users route is not protected

### ISSUE THREAD

**Issue by MeMeMax** [maljukan/typescript-node-rest-starter#5]
Hi,

for some reason I can just access the user route. Shouldn´t it be protected by the jwt getToken function? If I put a console.log into the getToken method I don´t get any output either.

If I put expressJwt({secret: 'shhhhhhared-secret'}) directly to the request like this:

`app.get('/user',
  jwt({secret: 'shhhhhhared-secret'}),
  function(req, res) {
    if (!req.user.admin) return res.sendStatus(401);
    res.sendStatus(200);
  });`

it works and I get 

> UnauthorizedError: No authorization token was found

Any Ideas?

**Comment by maljukan** [comment]
Yes, it's protected. You must provide the token. I'll get back with a curl example.

**Comment by MeMeMax** [comment]
No, I want to use the unless without the inline "jwt({secret: 'shhhhhhared-secret'})" but I don´t get the error.

**Comment by maljukan** [comment]
Thanks, it's a bug definitely

**Comment by MeMeMax** [comment]
Maybe it´s better to switch to passport.js if we can´t resolve this.

**Comment by MeMeMax** [comment]
Ok. But what is the use of unless if we have to add it to every single route?

**Comment by maljukan** [comment]
Thanks @MeMeMax , great inspection, i didn't connect that parameter with what it does following the description in `jwt-express`.
