### ISSUE TITLE
Protected vs unprotected routes?

### ISSUE THREAD

**Issue by MrChristofferson** [maljukan/typescript-node-rest-starter#8]
I noticed the thread in https://github.com/maljukan/typescript-node-rest-starter/issues/5, but now all the routes are protected. Was there a convention decided for how to implement the middleware?

**Comment by maljukan** [comment]
Thanks @MrChristofferson, I've swallowed some code, need to create unit tests asap.

**Comment by maljukan** [comment]
@MrChristofferson you can validate if the issue still exists. Thanks man!

**Comment by MrChristofferson** [comment]
@maljukan You sir, are the man. I'll test in and close when I get home 👍

**Comment by MrChristofferson** [comment]
Nice ;D
